#!/bin/sh /etc/rc.common
START=93

run_jmusupplicant()
{
    local enable
    local username
    local password
    local ifname
    local cmd
    config_get_bool enable $1 enable
    config_get username $1 username
    config_get password $1 password
    config_get ifname $1 ifname

    if [ $enable ] && [ $username ] && [ $password ] && [ $ifname ]; then
        local pinghost
        local ipaddr
        local mask
        local gateway
        local dns
        local echointerval
        local restartwait
        local netoperator
        local datafile

        config_get pinghost $1 pinghost
        config_get startmode $1 startmode
        config_get ipaddr $1 ipaddr
        config_get mask $1 mask
        config_get gateway $1 gateway
        config_get dns $1 dns
        config_get echointerval $1 echointerval
        config_get restartwait $1 restartwait
        config_get netoperator $1 netoperator
        config_get datafile $1 datafile

        if [ "$ipaddr" != "" ]; then cmd=$cmd" -i"$ipaddr;fi
        if [ "$mask" != "" ]; then cmd=$cmd" -m"$mask;fi
        if [ "$pinghost" != "0.0.0.0" ] &&  [ "$pinghost" != "" ]; then cmd=$cmd" -o"$pinghost;fi
        if [ "$gateway" != "0.0.0.0" ] &&  [ "$gateway" != "" ]; then cmd=$cmd" -g"$gateway;fi
        if [ "$dns" != "0.0.0.0" ] &&  [ "$dns" != "" ]; then cmd=$cmd" -s"$dns;fi
        if [ "$echointerval" != "30" ] &&  [ "$echointerval" != "" ]; then cmd=$cmd" -e"$echointerval;fi
        if [ "$restartwait" != "15" ] &&  [ "$restartwait" != "" ]; then cmd=$cmd" -r"$restartwait;fi
        if [ "$netoperator" != "0" ] && [ "$netoperator" != "" ]; then cmd=$cmd" -s"$netoperator;fi
        if [ "$datafile" != "/etc/jmusupplicant/" ] &&  [ "$datafile" != "" ]; then cmd=$cmd" -f"$datafile;fi

        /bin/ash -c "jmusupplicant -u$username -p$password -n$ifname -b3 -w $cmd"
    else
        /bin/ash -c "jmusupplicant -k"
    fi
}

start()
{
    config_load jmusupplicant
    config_foreach run_jmusupplicant jmusupplicant
}

stop()
{
    killall jmusupplicant
}

restart()
{
    jmusupplicant -k
    sleep 1
    config_load jmusupplicant
    config_foreach run_jmusupplicant jmusupplicant
}
